var input = document.getElementById("type-guess");
var awesomplete = new Awesomplete(input, {
	minChars: 1,
	maxItems: 7,
});

/* drugs */
var drugs = [["Atorvastatin"," ","(Lipitor)"],
				["Levothyroxine"," ","(Euthyrox, Levoxyl, Synthroid, Thyquidity, Tirosint, Unithroid)"],
				["Lisinopril"," ","(Qbrelis, Zestril)"],
				["Metformin"," ","(Glumetza, Riomet)"],
				["Metoprolol"," ","(Kapspargo Sprinkle, Lopressor, Toprol XL)"],
				["Amlodipine"," ","(Katerzia, Norvasc)"],
				["Albuterol"," ","(Proair, Proventil, Ventolin)"],
				["Omeprazole"," ","(Prilosec)"],
				["Losartan"," ","(Cozaar)"],
				["Gabapentin"," ","(Gralise, Horizant, Neurontin)"],
				["Hydrochlorothiazide"],
				["Sertraline"," ","(Zoloft)"],
				["Simvastatin"," ","(FloLipid, Zocor)"],
				["Montelukast"," ","(Singulair)"],
				["Acetaminophen","/ ","Hydrocodone"," ","(Lortab, Verdrocet, Xodol)"],
				["Pantoprazole"," ","(Protonix)"],
				["Furosemide"," ","(Lasix)"],
				["Fluticasone"," ","(ArmonAir, Arnuity Ellipta, Cutivate, Flovent, Xhance)"],
				["Escitalopram"," ","(Lexapro)"],
				["Fluoxetine"," ","(Prozac)"],
				["Rosuvastatin"," ","(Crestor, Ezallor Sprinkle)"],
				["Bupropion"," ","(Aplenzin, Forfivo XL, Wellbutrin)"],
				["Amoxicillin"],
				["Dextroamphetamine","/ ","Amphetamine"," ","(Adderall, Mydayis)"],
				["Trazodone"],
				["Duloxetine"," ","(Cymbalta, Drizalma Sprinkle)"],
				["Prednisone"," ","(Prednisone Intensol, Rayos)"],
				["Tamsulosin"," ","(Flomax)"],
				["Ibuprofen"," ","(Advil, Caldolor, IBU, Motrin, NeoProfen, Provil)"],
				["Citalopram"," ","(Celexa)"],
				["Meloxicam"," ","(Anjeso, Mobic, Vivlodex)"],
				["Pravastatin"],
				["Carvedilol"," ","(Coreg)"],
				["Potassium"," ","(K-Tab, Klor-Con, K-Phos, Urocit-K)"],
				["Tramadol"," ","(ConZip, Qdolo, Ultram)"],
				["Clopidogrel"," ","(Plavix)"],
				["Insulin Glargine"," ","(Basaglar, Lantus, Semglee, Toujeo)"],
				["Aspirin"," ","(Aspir-Low, Aspirtab, Durlaza, Ecotrin, GoodSense, Vazalore)"],
				["Atenolol"," ","(Tenormin)"],
				["Venlafaxine"," ","(Effexor XR)"],
				["Alprazolam"," ","(Xanax)"],
				["Ethinyl Estradiol","/ ","Norethindrone"," ","(Alyacen, Blisovi, Jinteli, Junel, Larin, Loestrin, Pirmella, Vyfemla)"],
				["Allopurinol"," ","(Aloprim, Zyloprim)"],
				["Lisinopril","/ ","Hydrochlorothiazide"," ","(Zestoretic)"],
				["Cyclobenzaprine"," ","(Amrix, Fexmid)"],
				["Clonazepam"," ","(Klonopin)"],
				["Zolpidem"," ","(Ambien, Edluar, Zolpimist)"],
				["Azithromycin"," ","(AzaSite, Zithromax)"],
				["Oxycodone"," ","(Oxaydo, Oxycontin, Roxicodone, Xtampza ER)"],
				["Warfarin"," ","(Jantoven)"],
				["Methylphenidate"," ","(Adhansia, Aptensio, Concerta, Cotempla, Daytrana, Jornay PM, Methylin, QuilliChew, Quillivant, Relexxii, Ritalin)"],
				["Apixaban"," ","(Eliquis)"],
				["Glipizide"," ","(Glucotrol)"],
				["Ergocalciferol"," ","(Drisdol, Ergocal)"],
				["Quetiapine"," ","(Seroquel)"],
				["Budesonide","/ ","Formoterol"," ","(Symbicort)"],
				["Estradiol"," ","(Climara, Dotti, Estrace, Estring, Estrogel, Femring, Imvexxy, Minivelle, Vagifem, Vivelle-Dot, Yuvafem)"],
				["Acetaminophen","/ ","Oxycodone"," ","(Endocet, Nalocet, Percocet, Prolate)"],
				["Ondansetron"," ","(Zofran, Zuplenz)"],
				["Naproxen"," ","(Aleve, Anaprox DS, Mediproxen, Naprelan, Naprosyn)"],
				["Glimepiride"," ","(Amaryl)"],
				["Spironolactone"," ","(Aldactone, CaroSpir)"],
				["Clonidine"," ","(Catapres, Duraclon, Kapvay, Nexiclon XR)"],
				["Insulin Lispro"," ","(Admelog, Humalog)"],
				["Loratadine"," ","(Claritin, Loradamed)"],
				["Cetirizine"," ","(Quzyttir, Zyrtec)"],
				["Topiramate"," ","(Eprontia, Qudexy XR, Topamax, Trokendi XR)"],
				["Lorazepam"," ","(Ativan, Loreev XR)"],
				["Ethinyl Estradiol","/ ","Norgestimate"," ","(Estarylla, Femynor, Mili, Mono-Linyah, Previfem, Sprintec, Tri-Lo-Marzia)"],
				["Lamotrigine"," ","(Lamictal, Subvenite)"],
				["Diltiazem"," ","(Cardizem, Cartia XT, Dilt-XR, Matzim LA, Taztia XT, Tiadylt ER, Tiazac)"],
				["Losartan","/ ","Hydrochlorothiazide"," ","(Hyzaar)"],
				["Diclofenac"," ","(Cambia, Cataflam, Diclozor, Flector, Licart, Lofena, Pennsaid, Profinac, Voltaren, Xrylix, Zipsor, Zorvolex)"],
				["Hydroxyzine"," ","(Vistaril)"],
				["Buspirone"],
				["Latanoprost"," ","(Xalatan, Xelpros)"],
				["Paroxetine"," ","(Brisdelle, Paxil, Pexeva)"],
				["Lisdexamfetamine"," ","(Vyvanse)"],
				["Fluticasone","/ ","Salmeterol"," ","(Advair, AirDuo, Wixela)"],
				["Pregabalin"," ","(Lyrica)"],
				["Propranolol"," ","(Hemangeol, Inderal, InnoPran)"],
				["Cephalexin"],
				["Cholecalciferol"," ","(D-Vi-Sol)"],
				["Insulin Aspart"," ","(Fiasp, NovoLog)"],
				["Finasteride"," ","(Propecia, Proscar)"],
				["Fenofibrate"," ","(Antara, Fenoglide, Fibricor, Lipofen, Tricor, Trilipix)"],
				["Sitagliptin"," ","(Januvia)"],
				["Folic Acid"],
				["Doxycycline"," ","(Acticlate, Avidoxy, Doryx, Lymepak, Mondoxyne, Oracea, TargaDOX, Vibramycin)"],
				["Rivaroxaban"," ","(Xarelto)"],
				["Tizanidine"," ","(Zanaflex)"],
				["Amoxicillin","/ ","Clavulanate"," ","(Augmentin)"],
				["Amitriptyline"],
				["Lovastatin"," ","(Altoprev)"],
				["Alendronate"," ","(Binosto, Fosamax)"],
				["Levetiracetam"," ","(Elepsia, Keppra, Roweepra, Spritam)"],
				["Sumatriptan"," ","(Imitrex, Onzetra, Sumavel, Tosymra, Zembrace)"],
				["Hydralazine"],
				["Sulfamethoxazole","/ ","Trimethoprim"," ","(Bactrim, Sulfatrim)"],
				["Aripiprazole"," ","(Abilify)"],
				["Celecoxib"," ","(Celebrex, Elyxyb)"],
				["Ferrous Sulfate"," ","(Fer-In-Sol, FeroSul, FerroSol, Slow Fe)"],
				["Famotidine"," ","(Pepcid)"],
				["Benzonatate"],
				["Mirtazapine"," ","(Remeron)"],
				["Triamcinolone"," ","(Aristocort, Hexatrione, Kenalog, Nasacort, Oracort, Triesence, Xipere, Zilretta)"],
				["Ezetimibe"," ","(Zetia)"],
				["Fluticasone","/ ","Vilanterol"," ","(Breo Ellipta)"],
				["Valacyclovir"," ","(Valtrex)"],
				["Methotrexate"," ","(Otrexup, Rasuvo, RediTrex, Trexall, Xatmep)"],
				["Oxybutynin"," ","(Ditropan, Gelnique, Oxytrol)"],
				["Ciprofloxacin"," ","(Cetraxal, Cipro, Ciloxan, Otiprio)"],
				["Valproate"," ","(Depakote)"],
				["Triamterene","/ ","Hydrochlorothiazide"," ","(Maxzide)"],
				["Desiccated Thyroid"," ","(Armor Thyroid, NP Thyroid)"],
				["Diazepam"," ","(Diastat, Valium, Valtoco)"],
				["Nifedipine"," ","(Procardia)"],
				["Clindamycin"," ","(Cleocin, Clindacin, Clindesse, Evoclin)"],
				["Donepezil"," ","(Aricept)"],
				["Insulin Detemir"," ","(Levemir)"],
				["Hydroxychloroquine"," ","(Plaquenil)"],
				["Isosorbide"," ","(Isordil)"],
				["Ethinyl Estradiol","/ ","Levonorgestrel"," ","(Aviane, Camrese, Falmina, Larissa, Orysthia, Seasonique, Setlakin, Sronyx, Twirla, Vienva)"],
				["Baclofen"," ","(Fleqsuvy, Gablofen, Lioresal, Ozobax)"],
				["Testosterone"," ","(Androderm, AndroGel, Aveed, Fortesta, Jatenzo, Testim, Testopel, Vogelxo, Xyosted)"],
				["Esomeprazole"," ","(Nexium)"],
				["Ethinyl Estradiol","/ ","Desogestrel"," ","(Apri, Emoquette, Isibloom, Mircette, Pimtrea, Reclipsen, Simliya, Velivet)"],
				["Oseltamivir"," ","(Tamiflu)"],
				["Benazepril"," ","(Lotensin)"],
				["Dexmethylphenidate"," ","(Focalin)"],
				["Tiotropium"," ","(Spiriva)"],
				["Fluconazole"," ","(Diflucan)"],
				["Dulaglutide"," ","(Trulicity)"],
				["Chlorthalidone"," ","(Thalitone)"],
				["Methocarbamol"," ","(Robaxin)"],
				["Enalapril"," ","(Epaned, Vasotec)"],
				["Metronidazole"," ","(Flagyl, Metrogel, Nidagel, Noritate)"],
				["Prednisolone"," ","(Millipred, Orapred, Pediapred, Pred Forte)"],
				["Guanfacine"," ","(Intuniv)"],
				["Verapamil"," ","(Calan, Verelan)"],
				["Liraglutide"," ","(Saxenda, Victoza)"],
				["Norethindrone"," ","(Aygestin, Camila, Deblitane, Incassia, Lyza, Norlyda, Norlyroc, Sharobel, Tulana)"],
				["Ropinirole"],
				["Acetaminophen"," ","(Aurophen, Mapap, Ofirmev, Tylenol)"],
				["Empagliflozin"," ","(Jardiance)"],
				["Hydrocortisone"," ","(Anucort-HC, Anusol, Cortef, Cortenema, Cortifoam, Locoid, NuCort, Pandel, Preparation H, Proctocort, Proctosol)"],
				["Ethinyl Estradiol","/ ","Drospirenone"," ","(Loryna, Ocella, Vestura, Yasmin, YAZ, Zumandimine)"],
				["Risperidone"," ","(Perseris, Risperdal)"],
				["Meclizine"," ","(Antivert, Bonine)"],
				["Albuterol","/ ","Ipratropium"," ","(Combivent Respimat)"],
				["Adalimumab"," ","(Humira)"],
				["Nortriptyline"," ","(Pamelor)"],
				["Valsartan"," ","(Diovan)"],
				["Cyanocobalamin"," ","(Dodex, Nascobal)"],
				["Ethinyl Estradiol","/ ","Etonogestrel"," ","(EluRyng, NuvaRing)"],
				["Acyclovir"," ","(Sitavig, Zovirax)"],
				["Phentermine"," ","(Adipex-P, Lomaira)"],
				["Cefdinir"," ","(Omnicef)"],
				["Timolol"," ","(Betimol, Istalol, Timoptic)"],
				["Methylprednisolone"," ","(Medrol)"],
				["Oxcarbazepine"," ","(Oxtellar XR, Trileptal)"],
				["Morphine"," ","(Duramorph, Infumorph, Mitigo, MS Contin)"],
				["Olmesartan"," ","(Benicar)"],
				["Dicyclomine"," ","(Bentyl)"],
				["Pramipexole"," ","(Mirapex)"],
				["Azelastine"],
				["Insulin Degludec"," ","(Tresiba)"],
				["Memantine"," ","(Namenda)"],
				["Prazosin"," ","(Minipress)"],
				["Ketoconazole"," ","(Extina, Ketodan, Nizoral, Xolegel)"],
				["Rizatriptan"," ","(Maxalt)"],
				["Acetaminophen","/ ","Codeine"],
				["Promethazine"," ","(Phenergan)"],
				["Metformin","/ ","Sitagliptin"," ","(Janumet)"],
				["Anastrozole"," ","(Arimidex)"],
				["Desvenlafaxine"," ","(Pristiq)"],
				["Ramipril"," ","(Altace)"],
				["Pioglitazone"," ","(Actos)"],
				["Clobetasol"," ","(Clobetavix, Clobex, Clodan, Impeklo, Impoyz, Olux, Tasoprol, Temovate, Tovet)"],
				["Irbesartan"," ","(Avapro)"],
				["Levofloxacin"],
				["Amiodarone"," ","(Nexterone, Pacerone)"],
				["Nitroglycerin"," ","(GoNitro, Nitro-Bid, Nitro-Dur, Nitro-Time, Nitrolingual, NitroMist, NitroStat, Rectiv)"],
				["Olanzapine"," ","(Zyprexa)"],
				["Sucralfate"," ","(Carafate)"],
				["Docusate"," ","(Colace, DOK, Pedia-Lax, Silace)"],
				["Progesterone"," ","(Crinone, Endometrin, Prometrium)"],
				["Mirabegron"," ","(Myrbetriq)"],
				["Mupirocin"," ","(Centany)"],
				["Nebivolol"," ","(Bystolic)"],
				["Nitrofurantoin"," ","(Macrobid, Macrodantin)"],
				["Levocetirizine"," ","(Xyzal)"],
				["Methimazole"],
				["Cyclosporine"," ","(Cequa, Gengraf, Neoral, Restasis, SandIMMUNE, Verkazia)"],
				["Sildenafil"," ","(Revatio, Viagra)"],
				["Carbamazepine"," ","(Carbatrol, Epitol, Equetro, Tegretol)"],
				["Labetalol"],
				["Calcium","/ ","Cholecalciferol"," ","(Caltrate, Os-Cal)"],
				["Lansoprazole"," ","(Prevacid)"],
				["Budesonide"," ","(Ortikos, Pulmicort, Tarpeyo, Uceris)"],
				["Colchicine"," ","(Colcrys, Gloperba, Mitigare)"],
				["Terazosin"],
				["Umeclidinium","/ ","Vilanterol"," ","(Anoro Ellipta)"],
				["Lithium"," ","(Lithobid)"],
				["Digoxin"," ","(Digitek, Digox, Lanoxin)"],
				["Dorzolamide","/ ","Timolol"," ","(Cosopt)"],
				["Melatonin"],
				["Insulin NPH","/ ","Insulin Regular"," ","(Humulin 70/30, Novolin 70/30)"],
				["Doxazosin"," ","(Cardura)"],
				["Ranolazine"," ","(Ranexa)"],
				["Gemfibrozil"," ","(Lopid)"],
				["Amlodipine","/ ","Benazepril"," ","(Lotrel)"],
				["Temazepam"," ","(Restoril)"],
				["Flecainide"],
				["Ticagrelor"," ","(Brilinta)"],
				["Brimonidine"," ","(Alphagan P, Lumify, Mirvaso)"],
				["Dexlansoprazole"," ","(Dexilant)"],
				["Lidocaine"," ","(Akten, Lidoderm, Lidomark, Salonpas, Xylocaine)"],
				["Lurasidone"," ","(Latuda)"],
				["Benztropine"],
				["Nystatin"," ","(Nyamyc, Nystop)"],
				["Eszopiclone"," ","(Lunesta)"],
				["Sacubitril","/ ","Valsartan"," ","(Entresto)"],
				["Calcium"," ","Citrate"],
				["Sodium Chloride"," ","(Ayr, Deep Sea Nasal Spray, HyperSal, Muro 128, Ocean Nasal Spray, Pretz)"],
				["Torsemide"," ","(Soaanz)"],
				["Butalbital","/ ","Acetaminophen","/ ","Caffeine"," ","(Bac, Esgic, Fioricet, Vtol LQ, Zebutal)"],
				["Mesalamine"," ","(Apriso, Asacol, Canasa, Delzicol, Lialda, Pentasa, Rowasa)"],
				["Liothyronine"," ","(Cytomel, Triostat)"],
				["Buprenorphine"," ","(Belbuca, Buprenex, Butrans, Sublocade)"],
				["Ofloxacin"," ","(Ocuflox)"],
				["Erythromycin"," ","(E.E.S., Ery-Tab, Erygel)"],
				["Doxepin"," ","(Prudoxin, Silenor, Zonalon)"],
				["Semaglutide"," ","(Ozempic, Rybelsus, Wegovy)"],
				["Hydromorphone"," ","(Dilaudid)"],
				["Penicillin V Potassium"],
				["Valsartan","/ ","Hydrochlorothiazide"," ","(Diovan HCT)"],
				["Beclomethasone"," ","(Beconase, Qnasl, Qvar)"],
				["Brimonidine","/ ","Timolol"," ","(Combigan)"],
				["Bumetanide"," ","(Bumex)"],
				["Letrozole"," ","(Femara)"],
				["Linagliptin"," ","(Tradjenta)"],
				["Tretinoin"," ","(Altreno, Atralin, Refissa, Renova, Retin-A)"],
				["Minocycline"," ","(Amzeeq, CoreMino, Minocin, Minolira, Solodyn, Ximino, Zilxi)"],
				["Ipratropium"," ","(Atrovent)"],
				["Polyethylene Glycol 3350"," ","(Gavilax, Gialax, Glycolax, MiraLAX)"],
				["Umeclidinium"," ","(Incruse Ellipta)"],
				["Bisoprolol"],
				["Calcitriol"," ","(Rocaltrol, Vectical)"],
				["Varenicline"],
				["Epinephrine"," ","(Adrenalin, Auvi-Q, EpiPen, Symjepi)"],
				["Conjugated Estrogens"," ","(Premarin)"],
				["Glyburide"," ","(Glynase)"],
				["Guaifenesin"," ","(Mucinex, Robafen, Robitussin, Tussin)"],
				["Magnesium"],
				["Ethinyl Estradiol","/ ","Norgestrel"," ","(Cryselle, Elinest, Ogestrel)"],
				["Sotalol"," ","(Betapace, Sorine, Sotylize)"],
				["Bimatoprost"," ","(Durysta, Latisse, Lumigan)"],
				["Insulin NPH"," ","(Humulin N, Novolin N)"],
				["Medroxyprogesterone"," ","(Provera)"],
				["Tamoxifen"," ","(Soltamox)"],
				["Mometasone"," ","(Asmanex, Nasonex)"],
				["Sulfasalazine"," ","(Azulfidine)"],
				["Dorzolamide"," ","(Trusopt)"],
				["Ketorolac"," ","(Acular, Acuvail, Sprix)"],
				["Indomethacin"," ","(Indocin, Tivorbex)"],
				["Atomoxetine"," ","(Strattera)"],
				["Olopatadine"," ","(Pataday, Patanase)"],
				["Telmisartan"," ","(Micardis)"],
				["Phenytoin"," ","(Dilantin, Phenytek)"],
				["Buprenorphine","/ ","Naloxone"," ","(Suboxone, Zubsolv)"],
				["Raloxifene"," ","(Evista)"],
				["Tobramycin","/ ","Dexamethasone"," ","(TobraDex)"],
				["Naltrexone"," ","(Vivitrol)"],
				["Polymyxin B","/ ","Trimethoprim"," ","(Polytrim)"],
				["Terbinafine"," ","(Lamisil)"],
				["Fentanyl"," ","(Actiq, Fentora, Lazanda, Subsys)"],
				["Diphenhydramine"," ","(Banophen, Benadryl, Diphenhist, ZzzQuil)"],
				["Bisoprolol","/ ","Hydrochlorothiazide"," ","(Ziac)"],
				["Pancrelipase"," ","(Creon, Pancreaze, Pertzye, Viokace, Zenpep)"],
				["Zonisamide"," ","(Zonegran)"],
				["Fexofenadine"," ","(Allegra)"],
				["Erenumab"," ","(Aimovig)"],
				["Linaclotide"," ","(Linzess)"],
				["Brompheniramine","/ ","Pseudoephedrine","/ ","Dextromethorphan"," ","(Bromfed DM)"],
				["Omega-3-Acid Ethyl Esters"," ","(Lovaza)"],
				["Dimethyl Fumarate"," ","(Tecfidera)"],
				["Tadalafil"," ","(Adcirca, Alyq, Cialis)"],
				["Canagliflozin"," ","(Invokana)"],
				["Emtricitabine","/ ","Tenofovir Disoproxil Fumarate"," ","(Truvada)"],
				["Tolterodine"," ","(Detrol)"],
				["Etanercept"," ","(Enbrel)"],
				["Quinapril"," ","(Accupril)"],
				["Docusate","/ ","Senna"," ","(Senokot-S)"],
				["Betamethasone"," ","(Diprolene, Luxiq, Sernivo)"],
				["Solifenacin"," ","(Vesicare)"],
				["Insulin Regular"," ","(Humulin R, Novolin R)"],
				["Chlorhexidine"," ","(Betasept, Hibiclens, Peridex, Periogard)"],
				["Fluocinonide"," ","(Vanos)"]];

var listDrugs = awesomplete.list = ["Atorvastatin (Lipitor)",
				"Levothyroxine (Euthyrox, Levoxyl, Synthroid, Thyquidity, Tirosint, Unithroid)",
				"Lisinopril (Qbrelis, Zestril)",
				"Metformin (Glumetza, Riomet)",
				"Metoprolol (Kapspargo Sprinkle, Lopressor, Toprol XL)",
				"Amlodipine (Katerzia, Norvasc)",
				"Albuterol (Proair, Proventil, Ventolin)",
				"Omeprazole (Prilosec)",
				"Losartan (Cozaar)",
				"Gabapentin (Gralise, Horizant, Neurontin)",
				"Hydrochlorothiazide",
				"Sertraline (Zoloft)",
				"Simvastatin (FloLipid, Zocor)",
				"Montelukast (Singulair)",
				"Acetaminophen/ Hydrocodone (Lortab, Verdrocet, Xodol)",
				"Pantoprazole (Protonix)",
				"Furosemide (Lasix)",
				"Fluticasone (ArmonAir, Arnuity Ellipta, Cutivate, Flovent, Xhance)",
				"Escitalopram (Lexapro)",
				"Fluoxetine (Prozac)",
				"Rosuvastatin (Crestor, Ezallor Sprinkle)",
				"Bupropion (Aplenzin, Forfivo XL, Wellbutrin)",
				"Amoxicillin",
				"Dextroamphetamine/ Amphetamine (Adderall, Mydayis)",
				"Trazodone",
				"Duloxetine (Cymbalta, Drizalma Sprinkle)",
				"Prednisone (Prednisone Intensol, Rayos)",
				"Tamsulosin (Flomax)",
				"Ibuprofen (Advil, Caldolor, IBU, Motrin, NeoProfen, Provil)",
				"Citalopram (Celexa)",
				"Meloxicam (Anjeso, Mobic, Vivlodex)",
				"Pravastatin",
				"Carvedilol (Coreg)",
				"Potassium (K-Tab, Klor-Con, K-Phos, Urocit-K)",
				"Tramadol (ConZip, Qdolo, Ultram)",
				"Clopidogrel (Plavix)",
				"Insulin Glargine (Basaglar, Lantus, Semglee, Toujeo)",
				"Aspirin (Aspir-Low, Aspirtab, Durlaza, Ecotrin, GoodSense, Vazalore)",
				"Atenolol (Tenormin)",
				"Venlafaxine (Effexor XR)",
				"Alprazolam (Xanax)",
				"Ethinyl Estradiol/ Norethindrone (Alyacen, Blisovi, Jinteli, Junel, Larin, Loestrin, Pirmella, Vyfemla)",
				"Allopurinol (Aloprim, Zyloprim)",
				"Lisinopril/ Hydrochlorothiazide (Zestoretic)",
				"Cyclobenzaprine (Amrix, Fexmid)",
				"Clonazepam (Klonopin)",
				"Zolpidem (Ambien, Edluar, Zolpimist)",
				"Azithromycin (AzaSite, Zithromax)",
				"Oxycodone (Oxaydo, Oxycontin, Roxicodone, Xtampza ER)",
				"Warfarin (Jantoven)",
				"Methylphenidate (Adhansia, Aptensio, Concerta, Cotempla, Daytrana, Jornay PM, Methylin, QuilliChew, Quillivant, Relexxii, Ritalin)",
				"Apixaban (Eliquis)",
				"Glipizide (Glucotrol)",
				"Ergocalciferol (Drisdol, Ergocal)",
				"Quetiapine (Seroquel)",
				"Budesonide/ Formoterol (Symbicort)",
				"Estradiol (Climara, Dotti, Estrace, Estring, Estrogel, Femring, Imvexxy, Minivelle, Vagifem, Vivelle-Dot, Yuvafem)",
				"Acetaminophen/ Oxycodone (Endocet, Nalocet, Percocet, Prolate)",
				"Ondansetron (Zofran, Zuplenz)",
				"Naproxen (Aleve, Anaprox DS, Mediproxen, Naprelan, Naprosyn)",
				"Glimepiride (Amaryl)",
				"Spironolactone (Aldactone, CaroSpir)",
				"Clonidine (Catapres, Duraclon, Kapvay, Nexiclon XR)",
				"Insulin Lispro (Admelog, Humalog)",
				"Loratadine (Claritin, Loradamed)",
				"Cetirizine (Quzyttir, Zyrtec)",
				"Topiramate (Eprontia, Qudexy XR, Topamax, Trokendi XR)",
				"Lorazepam (Ativan, Loreev XR)",
				"Ethinyl Estradiol/ Norgestimate (Estarylla, Femynor, Mili, Mono-Linyah, Previfem, Sprintec, Tri-Lo-Marzia)",
				"Lamotrigine (Lamictal, Subvenite)",
				"Diltiazem (Cardizem, Cartia XT, Dilt-XR, Matzim LA, Taztia XT, Tiadylt ER, Tiazac)",
				"Losartan/ Hydrochlorothiazide (Hyzaar)",
				"Diclofenac (Cambia, Cataflam, Diclozor, Flector, Licart, Lofena, Pennsaid, Profinac, Voltaren, Xrylix, Zipsor, Zorvolex)",
				"Hydroxyzine (Vistaril)",
				"Buspirone",
				"Latanoprost (Xalatan, Xelpros)",
				"Paroxetine (Brisdelle, Paxil, Pexeva)",
				"Lisdexamfetamine (Vyvanse)",
				"Fluticasone/ Salmeterol (Advair, AirDuo, Wixela)",
				"Pregabalin (Lyrica)",
				"Propranolol (Hemangeol, Inderal, InnoPran)",
				"Cephalexin",
				"Cholecalciferol (D-Vi-Sol)",
				"Insulin Aspart (Fiasp, NovoLog)",
				"Finasteride (Propecia, Proscar)",
				"Fenofibrate (Antara, Fenoglide, Fibricor, Lipofen, Tricor, Trilipix)",
				"Sitagliptin (Januvia)",
				"Folic Acid",
				"Doxycycline (Acticlate, Avidoxy, Doryx, Lymepak, Mondoxyne, Oracea, TargaDOX, Vibramycin)",
				"Rivaroxaban (Xarelto)",
				"Tizanidine (Zanaflex)",
				"Amoxicillin/ Clavulanate (Augmentin)",
				"Amitriptyline",
				"Lovastatin (Altoprev)",
				"Alendronate (Binosto, Fosamax)",
				"Levetiracetam (Elepsia, Keppra, Roweepra, Spritam)",
				"Sumatriptan (Imitrex, Onzetra, Sumavel, Tosymra, Zembrace)",
				"Hydralazine",
				"Sulfamethoxazole/ Trimethoprim (Bactrim, Sulfatrim)",
				"Aripiprazole (Abilify)",
				"Celecoxib (Celebrex, Elyxyb)",
				"Ferrous Sulfate (Fer-In-Sol, FeroSul, FerroSol, Slow Fe)",
				"Famotidine (Pepcid)",
				"Benzonatate",
				"Mirtazapine (Remeron)",
				"Triamcinolone (Aristocort, Hexatrione, Kenalog, Nasacort, Oracort, Triesence, Xipere, Zilretta)",
				"Ezetimibe (Zetia)",
				"Fluticasone/ Vilanterol (Breo Ellipta)",
				"Valacyclovir (Valtrex)",
				"Methotrexate (Otrexup, Rasuvo, RediTrex, Trexall, Xatmep)",
				"Oxybutynin (Ditropan, Gelnique, Oxytrol)",
				"Ciprofloxacin (Cetraxal, Cipro, Ciloxan, Otiprio)",
				"Valproate (Depakote)",
				"Triamterene/ Hydrochlorothiazide (Maxzide)",
				"Desiccated Thyroid (Armor Thyroid, NP Thyroid)",
				"Diazepam (Diastat, Valium, Valtoco)",
				"Nifedipine (Procardia)",
				"Clindamycin (Cleocin, Clindacin, Clindesse, Evoclin)",
				"Donepezil (Aricept)",
				"Insulin Detemir (Levemir)",
				"Hydroxychloroquine (Plaquenil)",
				"Isosorbide (Isordil)",
				"Ethinyl Estradiol/ Levonorgestrel (Aviane, Camrese, Falmina, Larissa, Orysthia, Seasonique, Setlakin, Sronyx, Twirla, Vienva)",
				"Baclofen (Fleqsuvy, Gablofen, Lioresal, Ozobax)",
				"Testosterone (Androderm, AndroGel, Aveed, Fortesta, Jatenzo, Testim, Testopel, Vogelxo, Xyosted)",
				"Esomeprazole (Nexium)",
				"Ethinyl Estradiol/ Desogestrel (Apri, Emoquette, Isibloom, Mircette, Pimtrea, Reclipsen, Simliya, Velivet)",
				"Oseltamivir (Tamiflu)",
				"Benazepril (Lotensin)",
				"Dexmethylphenidate (Focalin)",
				"Tiotropium (Spiriva)",
				"Fluconazole (Diflucan)",
				"Dulaglutide (Trulicity)",
				"Chlorthalidone (Thalitone)",
				"Methocarbamol (Robaxin)",
				"Enalapril (Epaned, Vasotec)",
				"Metronidazole (Flagyl, Metrogel, Nidagel, Noritate)",
				"Prednisolone (Millipred, Orapred, Pediapred, Pred Forte)",
				"Guanfacine (Intuniv)",
				"Verapamil (Calan, Verelan)",
				"Liraglutide (Saxenda, Victoza)",
				"Norethindrone (Aygestin, Camila, Deblitane, Incassia, Lyza, Norlyda, Norlyroc, Sharobel, Tulana)",
				"Ropinirole",
				"Acetaminophen (Aurophen, Mapap, Ofirmev, Tylenol)",
				"Empagliflozin (Jardiance)",
				"Hydrocortisone (Anucort-HC, Anusol, Cortef, Cortenema, Cortifoam, Locoid, NuCort, Pandel, Preparation H, Proctocort, Proctosol)",
				"Ethinyl Estradiol/ Drospirenone (Loryna, Ocella, Vestura, Yasmin, YAZ, Zumandimine)",
				"Risperidone (Perseris, Risperdal)",
				"Meclizine (Antivert, Bonine)",
				"Albuterol/ Ipratropium (Combivent Respimat)",
				"Adalimumab (Humira)",
				"Nortriptyline (Pamelor)",
				"Valsartan (Diovan)",
				"Cyanocobalamin (Dodex, Nascobal)",
				"Ethinyl Estradiol/ Etonogestrel (EluRyng, NuvaRing)",
				"Acyclovir (Sitavig, Zovirax)",
				"Phentermine (Adipex-P, Lomaira)",
				"Cefdinir (Omnicef)",
				"Timolol (Betimol, Istalol, Timoptic)",
				"Methylprednisolone (Medrol)",
				"Oxcarbazepine (Oxtellar XR, Trileptal)",
				"Morphine (Duramorph, Infumorph, Mitigo, MS Contin)",
				"Olmesartan (Benicar)",
				"Dicyclomine (Bentyl)",
				"Pramipexole (Mirapex)",
				"Azelastine",
				"Insulin Degludec (Tresiba)",
				"Memantine (Namenda)",
				"Prazosin (Minipress)",
				"Ketoconazole (Extina, Ketodan, Nizoral, Xolegel)",
				"Rizatriptan (Maxalt)",
				"Acetaminophen/ Codeine",
				"Promethazine (Phenergan)",
				"Metformin/ Sitagliptin (Janumet)",
				"Anastrozole (Arimidex)",
				"Desvenlafaxine (Pristiq)",
				"Ramipril (Altace)",
				"Pioglitazone (Actos)",
				"Clobetasol (Clobetavix, Clobex, Clodan, Impeklo, Impoyz, Olux, Tasoprol, Temovate, Tovet)",
				"Irbesartan (Avapro)",
				"Levofloxacin",
				"Amiodarone (Nexterone, Pacerone)",
				"Nitroglycerin (GoNitro, Nitro-Bid, Nitro-Dur, Nitro-Time, Nitrolingual, NitroMist, NitroStat, Rectiv)",
				"Olanzapine (Zyprexa)",
				"Sucralfate (Carafate)",
				"Docusate (Colace, DOK, Pedia-Lax, Silace)",
				"Progesterone (Crinone, Endometrin, Prometrium)",
				"Mirabegron (Myrbetriq)",
				"Mupirocin (Centany)",
				"Nebivolol (Bystolic)",
				"Nitrofurantoin (Macrobid, Macrodantin)",
				"Levocetirizine (Xyzal)",
				"Methimazole",
				"Cyclosporine (Cequa, Gengraf, Neoral, Restasis, SandIMMUNE, Verkazia)",
				"Sildenafil (Revatio, Viagra)",
				"Carbamazepine (Carbatrol, Epitol, Equetro, Tegretol)",
				"Labetalol",
				"Calcium/ Cholecalciferol (Caltrate, Os-Cal)",
				"Lansoprazole (Prevacid)",
				"Budesonide (Ortikos, Pulmicort, Tarpeyo, Uceris)",
				"Colchicine (Colcrys, Gloperba, Mitigare)",
				"Terazosin",
				"Umeclidinium/ Vilanterol (Anoro Ellipta)",
				"Lithium (Lithobid)",
				"Digoxin (Digitek, Digox, Lanoxin)",
				"Dorzolamide/ Timolol (Cosopt)",
				"Melatonin",
				"Insulin NPH/ Insulin Regular (Humulin 70/30, Novolin 70/30)",
				"Doxazosin (Cardura)",
				"Ranolazine (Ranexa)",
				"Gemfibrozil (Lopid)",
				"Amlodipine/ Benazepril (Lotrel)",
				"Temazepam (Restoril)",
				"Flecainide",
				"Ticagrelor (Brilinta)",
				"Brimonidine (Alphagan P, Lumify, Mirvaso)",
				"Dexlansoprazole (Dexilant)",
				"Lidocaine (Akten, Lidoderm, Lidomark, Salonpas, Xylocaine)",
				"Lurasidone (Latuda)",
				"Benztropine",
				"Nystatin (Nyamyc, Nystop)",
				"Eszopiclone (Lunesta)",
				"Sacubitril/ Valsartan (Entresto)",
				"Calcium Citrate",
				"Sodium Chloride (Ayr, Deep Sea Nasal Spray, HyperSal, Muro 128, Ocean Nasal Spray, Pretz)",
				"Torsemide (Soaanz)",
				"Butalbital/ Acetaminophen/ Caffeine (Bac, Esgic, Fioricet, Vtol LQ, Zebutal)",
				"Mesalamine (Apriso, Asacol, Canasa, Delzicol, Lialda, Pentasa, Rowasa)",
				"Liothyronine (Cytomel, Triostat)",
				"Buprenorphine (Belbuca, Buprenex, Butrans, Sublocade)",
				"Ofloxacin (Ocuflox)",
				"Erythromycin (E.E.S., Ery-Tab, Erygel)",
				"Doxepin (Prudoxin, Silenor, Zonalon)",
				"Semaglutide (Ozempic, Rybelsus, Wegovy)",
				"Hydromorphone (Dilaudid)",
				"Penicillin V Potassium",
				"Valsartan/ Hydrochlorothiazide (Diovan HCT)",
				"Beclomethasone (Beconase, Qnasl, Qvar)",
				"Brimonidine/ Timolol (Combigan)",
				"Bumetanide (Bumex)",
				"Letrozole (Femara)",
				"Linagliptin (Tradjenta)",
				"Tretinoin (Altreno, Atralin, Refissa, Renova, Retin-A)",
				"Minocycline (Amzeeq, CoreMino, Minocin, Minolira, Solodyn, Ximino, Zilxi)",
				"Ipratropium (Atrovent)",
				"Polyethylene Glycol 3350 (Gavilax, Gialax, Glycolax, MiraLAX)",
				"Umeclidinium (Incruse Ellipta)",
				"Bisoprolol",
				"Calcitriol (Rocaltrol, Vectical)",
				"Varenicline",
				"Epinephrine (Adrenalin, Auvi-Q, EpiPen, Symjepi)",
				"Conjugated Estrogens (Premarin)",
				"Glyburide (Glynase)",
				"Guaifenesin (Mucinex, Robafen, Robitussin, Tussin)",
				"Magnesium",
				"Ethinyl Estradiol/ Norgestrel (Cryselle, Elinest, Ogestrel)",
				"Sotalol (Betapace, Sorine, Sotylize)",
				"Bimatoprost (Durysta, Latisse, Lumigan)",
				"Insulin NPH (Humulin N, Novolin N)",
				"Medroxyprogesterone (Provera)",
				"Tamoxifen (Soltamox)",
				"Mometasone (Asmanex, Nasonex)",
				"Sulfasalazine (Azulfidine)",
				"Dorzolamide (Trusopt)",
				"Ketorolac (Acular, Acuvail, Sprix)",
				"Indomethacin (Indocin, Tivorbex)",
				"Atomoxetine (Strattera)",
				"Olopatadine (Pataday, Patanase)",
				"Telmisartan (Micardis)",
				"Phenytoin (Dilantin, Phenytek)",
				"Buprenorphine/ Naloxone (Suboxone, Zubsolv)",
				"Raloxifene (Evista)",
				"Tobramycin/ Dexamethasone (TobraDex)",
				"Naltrexone (Vivitrol)",
				"Polymyxin B/ Trimethoprim (Polytrim)",
				"Terbinafine (Lamisil)",
				"Fentanyl (Actiq, Fentora, Lazanda, Subsys)",
				"Diphenhydramine (Banophen, Benadryl, Diphenhist, ZzzQuil)",
				"Bisoprolol/ Hydrochlorothiazide (Ziac)",
				"Pancrelipase (Creon, Pancreaze, Pertzye, Viokace, Zenpep)",
				"Zonisamide (Zonegran)",
				"Fexofenadine (Allegra)",
				"Erenumab (Aimovig)",
				"Linaclotide (Linzess)",
				"Brompheniramine/ Pseudoephedrine/ Dextromethorphan (Bromfed DM)",
				"Omega-3-Acid Ethyl Esters (Lovaza)",
				"Dimethyl Fumarate (Tecfidera)",
				"Tadalafil (Adcirca, Alyq, Cialis)",
				"Canagliflozin (Invokana)",
				"Emtricitabine/ Tenofovir Disoproxil Fumarate (Truvada)",
				"Tolterodine (Detrol)",
				"Etanercept (Enbrel)",
				"Quinapril (Accupril)",
				"Docusate/ Senna (Senokot-S)",
				"Betamethasone (Diprolene, Luxiq, Sernivo)",
				"Solifenacin (Vesicare)",
				"Insulin Regular (Humulin R, Novolin R)",
				"Chlorhexidine (Betasept, Hibiclens, Peridex, Periogard)",
				"Fluocinonide (Vanos)"];

/* class */

var drugClass = [["HMG-CoA Reductase Inhibitor"],
					["L-Thyroxine (T4)"],
					["Angiotensin-Converting Enzyme (ACE) Inhibitor"],
					["Biguanide"],
					["Beta","-","1"," ","Blocker"],
					["Dihydropyridine (DHP)"," ","Calcium Channel Blocker (CCB)"],
					["Beta","-","2"," ","Agonist"],
					["Proton Pump Inhibitor (PPI)"],
					["Angiotensin II Receptor Blocker (ARB)"],
					["GABA Analog"],
					["Thiazide"," ","Diuretic"],
					["Selective"," ","Serotonin"," ","Reuptake Inhibitor (SSRI)"],
					["HMG-CoA Reductase Inhibitor"],
					["Leukotriene Receptor Antagonist"],
					["Combination"," ","Opioid"," ","Analgesic"],
					["Proton Pump Inhibitor (PPI)"],
					["Loop"," ","Diuretic"],
					["Corticosteroid"],
					["Selective"," ","Serotonin"," ","Reuptake Inhibitor (SSRI)"],
					["Selective"," ","Serotonin"," ","Reuptake Inhibitor (SSRI)"],
					["HMG-CoA Reductase Inhibitor"],
					["Dopamine","-","Norepinephrine"," ","Reuptake Inhibitor (DNRI)"],
					["Penicillin"," ","Antibiotic"],
					["Stimulant"],
					["Serotonin"," ","Reuptake Inhibitor"],
					["Serotonin","-","Norepinephrine"," ","Reuptake Inhibitor (SNRI)"],
					["Corticosteroid"],
					["Alpha","-","1"," ","Antagonist"],
					["Non-Steroidal Anti-Inflammatory Drug (NSAID)"],
					["Selective"," ","Serotonin"," ","Reuptake Inhibitor (SSRI)"],
					["Non-Steroidal Anti-Inflammatory Drug (NSAID)"],
					["HMG-CoA Reductase Inhibitor"],
					["Non-Selective"," ","Beta"," ","Blocker"],
					["Potassium"],
					["Opioid"," ","Analgesic"],
					["P2Y12 Antagonist"],
					["Long-Acting"," ","Insulin"],
					["Salicylate"],
					["Beta","-","1"," ","Blocker"],
					["Serotonin","-","Norepinephrine"," ","Reuptake Inhibitor (SNRI)"],
					["Benzodiazepine"],
					["Estrogen","/ ","Progestin"],
					["Xanthine Oxidase Inhibitor"],
					["Angiotensin-Converting Enzyme (ACE) Inhibitor","/ ","Thiazide"," ","Diuretic"],
					["Skeletal Muscle Relaxant"],
					["Benzodiazepine"],
					["Hypnotic"],
					["Macrolide"," ","Antibiotic"],
					["Opioid"," ","Analgesic"],
					["Vitamin K Antagonist"],
					["Stimulant"],
					["Factor Xa Inhibitor"],
					["Sulfonylurea"],
					["Vitamin"," ","D2"],
					["Atypical"," ","Antipsychotic"],
					["Corticosteroid","/ ","Beta","-","2"," ","Agonist"],
					["Estrogen"],
					["Combination"," ","Opioid"," ","Analgesic"],
					["Serotonin"," ","5-HT3 Receptor Antagonist"],
					["Non-Steroidal Anti-Inflammatory Drug (NSAID)"],
					["Sulfonylurea"],
					["Aldosterone"," ","Antagonist","and ","Potassium Sparing"," ","Diuretic"],
					["Alpha","-","2"," ","Agonist"],
					["Rapid-Acting"," ","Insulin"],
					["Second Generation"," ","Histamine"," ","H1 Antagonist"],
					["Second Generation"," ","Histamine"," ","H1 Antagonist"],
					["Anticonvulsant"],
					["Benzodiazepine"],
					["Estrogen","/ ","Progestin"],
					["Anticonvulsant"],
					["Non-Dihydropyridine (DHP)"," ","Calcium Channel Blocker (CCB)"],
					["Angiotensin II Receptor Blocker (ARB)","/ ","Thiazide"," ","Diueretic"],
					["Non-Steroidal Anti-Inflammatory Drug (NSAID)"],
					["First Generation"," ","Histamine"," ","H1 Antagonist"],
					["Antianxiety Agent"],
					["Prostaglandin"],
					["Selective"," ","Serotonin"," ","Reuptake Inhibitor (SSRI)"],
					["Stimulant"],
					["Corticosteroid","/ ","Beta","-","2"," ","Agonist"],
					["GABA Analog"],
					["Non-Selective"," ","Beta"," ","Blocker"],
					["1st Generation"," ","Cephalosporin"," ","Antibiotic"],
					["Vitamin"," ","D3"],
					["Rapid-Acting"," ","Insulin"],
					["5-Alpha-Reductase Inhibitor"],
					["Fibric Acid"],
					["Dipeptidyl Peptidase-4 (DPP-4) Inhibitor"],
					["Vitamin"," ","B9"],
					["Tetracycline"," ","Antibiotic"],
					["Factor Xa Inhibitor"],
					["Alpha","-","2"," ","Agonist"],
					["Penicillin"," ","Antibiotic","/ ","Beta-Lactamase Inhibitor"],
					["Tricyclic Antidepressant"],
					["HMG-CoA Reductase Inhibitor"],
					["Bisphosphonate"],
					["Anticonvulsant"],
					["Serotonin"," ","5-HT1B,1D Receptor Antagonist"],
					["Vasodilator"],
					["Sulfonamide"," ","Antibiotic"],
					["Atypical"," ","Antipsychotic"],
					["Non-Steroidal Anti-Inflammatory Drug (NSAID)"],
					["Iron"],
					["Histamine"," ","H2 Antagonist"],
					["Antitussive"],
					["Alpha","-","2"," ","Antagonist"],
					["Corticosteroid"],
					["Antilipidemic Agent"],
					["Corticosteroid","/ ","Beta","-","2"," ","Agonist"],
					["Antiviral"],
					["Antifolate"],
					["Antispasmodic"],
					["Fluoroquinolone"," ","Antibiotic"],
					["Histone Deacetylase Inhibitor"],
					["Potassium Sparing"," ","Diuretic","/ ","Thiazide"," ","Diuretic"],
					["Thyroid Product"],
					["Benzodiazepine"],
					["Dihydropyridine (DHP)"," ","Calcium Channel Blocker (CCB)"],
					["Lincosamide"," ","Antibiotic"],
					["Acetylcholinesterase Inhibitor"],
					["Long-Acting"," ","Insulin"],
					["Aminoquinoline"],
					["Vasodilator"],
					["Estrogen","/ ","Progestin"],
					["Skeletal Muscle Relaxant"],
					["Androgen"],
					["Proton Pump Inhibitor (PPI)"],
					["Estrogen","/ ","Progestin"],
					["Neuraminidase Inhibitor"],
					["Angiotensin-Converting Enzyme (ACE) Inhibitor"],
					["Stimulant"],
					["Anticholinergic Agent"],
					["Antifungal"],
					["Glucagon-Like Peptide-1 (GLP-1) Receptor Antagonist"],
					["Thiazide-Like"," ","Diuretic"],
					["Skeletal Muscle Relaxant"],
					["Angiotensin-Converting Enzyme (ACE) Inhibitor"],
					["Miscellaneous"," ","Antibiotic"],
					["Corticosteroid"],
					["Alpha","-","2"," ","Agonist"],
					["Non-Dihydropyridine (DHP)"," ","Calcium Channel Blocker (CCB)"],
					["Glucagon-Like Peptide-1 (GLP-1) Receptor Antagonist"],
					["Progestin"],
					["Dopamine"," ","Agonist"],
					["Non-Opioid"," ","Analgesic"],
					["Sodium-Glucose Cotransporter 2 (SGLT2) Inhibitor"],
					["Corticosteroid"],
					["Estrogen","/ ","Progestin"],
					["Atypical"," ","Antipsychotic"],
					["First Generation"," ","Histamine"," ","H1 Antagonist"],
					["Beta","-","2"," ","Agonist","/ ","Anticholinergic Agent"],	
					["Tumor Necrosis Factor (TNF) Blocking Agent"],
					["Tricyclic Antidepressant"],
					["Angiotensin II Receptor Blocker (ARB)"],
					["Vitamin"," ","B12"],
					["Estrogen","/ ","Progestin"],
					["Antiviral"],
					["Stimulant"],
					["3rd Generation"," ","Cephalosporin"," ","Antibiotic"],
					["Non-Selective"," ","Beta"," ","Blocker"],
					["Corticosteroid"],
					["Anticonvulsant"],
					["Opioid"," ","Analgesic"],
					["Angiotensin II Receptor Blocker (ARB)"],
					["Anticholinergic Agent"],
					["Dopamine"," ","Agonist"],
					["Second Generation"," ","Histamine"," ","H1 Antagonist"],
					["Long-Acting"," ","Insulin"],
					["NMDA Receptor Antagonist"],
					["Alpha","-","1"," ","Antagonist"],
					["Antifungal"],
					["Serotonin"," ","5-HT1B,1D Receptor Antagonist"],
					["Combination"," ","Opioid"," ","Analgesic"],
					["First Generation"," ","Histamine"," ","H1 Antagonist"],
					["Biguanide","/ ","Dipeptidyl Peptidase 4 (DPP-4) Inhibitor"],
					["Aromatase Inhibitor"],
					["Serotonin","-","Norepinephrine"," ","Reuptake Inhibitor (SNRI)"],
					["Angiotensin-Converting Enzyme (ACE) Inhibitor"],
					["Thiazolidinedione"],
					["Corticosteroid"],
					["Angiotensin II Receptor Blocker (ARB)"],
					["Fluoroquinolone"," ","Antibiotic"],
					["Class III"," ","Antiarrhythmic Agent"],
					["Vasodilator"],
					["Atypical"," ","Antipsychotic"],
					["Gastrointestinal Agent"],
					["Stool Softener"],
					["Progestin"],
					["Beta","-","3"," ","Agonist"],
					["Topical"," ","Antibiotic"],
					["Beta","-","1"," ","Blocker"],
					["Miscellaneous"," ","Antibiotic"],
					["Second Generation"," ","Histamine"," ","H1 Antagonist"],
					["Antithyroid Agent"],
					["Calcineurin Inhibitor"],
					["Phosphodiesterase-5 (PDE5) Enzyme Inhibitor"],
					["Anticonvulsant"],
					["Non-Selective"," ","Beta"," ","Blocker"],
					["Calcium"," ","Salt","/ ","Vitamin"," ","D3"],
					["Proton Pump Inhibitor (PPI)"],
					["Corticosteroid"],
					["Antigout Agent"],
					["Alpha","-","1"," ","Antagonist"],
					["Anticholinergic Agent","/ ","Beta","-","2"," ","Agonist"],
					["Antimanic Agent"],
					["Cardiac Glycoside"],
					["Carbonic Anhydrase Inhibitor","/ ","Non-Selective"," ","Beta"," ","Blocker"],
					["Natural Supplement"],
					["Intermediate-Acting"," ","Insulin","/ ","Short-Acting"," ","Insulin"],
					["Alpha","-","1"," ","Antagonist"],
					["Antianginal Agent"],
					["Fibric Acid"],
					["Dihydropyridine (DHP)"," ","Calcium Channel Blocker (CCB)","/ ","Angiotensin-Converting Enzyme (ACE) Inhibitor"],
					["Benzodiazepine"],
					["Class Ic"," ","Antiarrhythmic Agent"],
					["P2Y12 Antagonist"],
					["Alpha","-","2"," ","Agonist"],
					["Proton Pump Inhibitor (PPI)"],
					["Local Anesthetic"],
					["Atypical"," ","Antipsychotic"],
					["Anticholinergic Agent"],
					["Antifungal"],
					["Hypnotic"],
					["Neprilysin Inhibitor","/ ","Angiotensin II Receptor Blocker (ARB)"],
					["Calcium"," ","Salt"],
					["Sodium"," ","Salt"],
					["Loop"," ","Diuretic"],
					["Barbiturate","/ ","Non-Opioid"," ","Analgesic","/ ","Stimulant"],
					["Salicylate"],
					["L-Triiodothyronine (T3)"],
					["Opioid Partial Agonist"],
					["Fluoroquinolone"," ","Antibiotic"],
					["Macrolide"," ","Antibiotic"],
					["Tricyclic Antidepressant"],
					["Glucagon-Like Peptide-1 (GLP-1) Receptor Antagonist"],
					["Opioid"," ","Analgesic"],
					["Penicillin"," ","Antibiotic"],
					["Angiotensin II Receptor Blocker (ARB)","/ ","Thiazide"," ","Diuretic"],
					["Corticosteroid"],
					["Alpha","-","2"," ","Agonist","/ ","Non-Selective"," ","Beta"," ","Blocker"],
					["Loop"," ","Diuretic"],
					["Aromatase Inhibitor"],
					["Dipeptidyl Peptidase-4 (DPP-4) Inhibitor"],
					["Retinoid"],
					["Tetracycline"," ","Antibiotic"],
					["Anticholinergic Agent"],
					["Osmotic"," ","Laxative"],
					["Anticholinergic Agent"],
					["Beta","-","1"," ","Blocker"],
					["Vitamin"," ","D Analog"],
					["Partial Nicotine Agonist"],
					["Alpha"," ","&"," ","Beta"," ","Agonist"],
					["Estrogen"],
					["Sulfonylurea"],
					["Expectorant"],
					["Supplement","/ ","Osmotic"," ","Laxative"],
					["Estrogen","/ ","Progestin"],
					["Non-Selective"," ","Beta"," ","Blocker"],
					["Prostaglandin"],
					["Intermediate-Acting"," ","Insulin"],
					["Progestin"],
					["Selective"," ","Estrogen"," ","Receptor Modulator (SERM)"],
					["Corticosteroid"],
					["Salicylate"],
					["Carbonic Anhydrase Inhibitor"],
					["Non-Steroidal Anti-Inflammatory Drug (NSAID)"],
					["Non-Steroidal Anti-Inflammatory Drug (NSAID)"],
					["Norepinephrine"," ","Reuptake Inhibitor"],
					["Second Generation"," ","Histamine"," ","H1 Antagonist"],
					["Angiotensin II Receptor Blocker (ARB)"],
					["Hydantoin"],
					["Opioid"," ","Analgesic","/ ","Partial Opioid Agonist"],
					["Selective"," ","Estrogen"," ","Receptor Modulator (SERM)"],
					["Aminoglycoside"," ","Antibiotic","/ ","Corticosteroid"],
					["Opioid Antagonist "],
					["Miscellaneous"," ","Antibiotic"],
					["Antifungal"],
					["Opioid"," ","Analgesic"],
					["First Generation"," ","Histamine"," ","H1 Antagonist"],
					["Beta","-","1"," ","Blocker","/ ","Thiazide"," ","Diuretic"],
					["Pancreatic Enzymes"],
					["Anticonvulsant"],
					["Second Generation"," ","Histamine"," ","H1 Antagonist"],
					["Calcitonin Gene-Related Peptide (CGRP) Receptor Antagonist"],
					["Guanylate Cyclase-C (GC-C) Agonist"],
					["First Generation"," ","Histamine"," ","H1 Antagonist","/ ","Alpha"," ","&"," ","Beta"," ","Agonist","/ ","Antitussive"],
					["Omega-3 Fatty Acids"],
					["Fumaric Acid Derivative"],
					["Phosphodiesterase-5 (PDE5) Enzyme Inhibitor"],
					["Sodium-Glucose Cotransporter 2 (SGLT2) Inhibitor"],
					["Reverse Transcriptase Inhibitor"],
					["Anticholinergic Agent"],
					["Tumor Necrosis Factor (TNF) Blocking Agent"],
					["Angiotensin-Converting Enzyme (ACE) Inhibitor"],
					["Stool Softener","/ ","Stimulant"," ","Laxative"],
					["Corticosteroid"],
					["Anticholinergic Agent"],
					["Short-Acting"," ","Insulin"],
					["Topical"," ","Antibiotic"],
					["Corticosteroid"]];

/* indications */

var drugIndication = [["Hypercholesterolemia"],
						["Hypothyroidism"],
						["HFrEF",", ","Hypertension",", ","ST-Elevation Myocardial Infarction"],
						["Type 2"," ","Diabetes"],
						["Angina",", ","HFrEF",", ","Hypertension",", ","Myocardial Infarction"],
						["Angina",", ","Hypertension"],
						["Asthma"],
						["GERD"],
						["Hypertension"],
						["Neuralgia",", ","Seizures"],
						["Edema",", ","Hypertension"],
						["Anxiety",", ","Depression",", ","Obsessive-Compulsive Disorder",", ","Posttraumatic Stress Disorder",", ","Premenstrual Dysphoric Disorder"],
						["Hypercholesterolemia"],
						["Allergies",", ","Asthma"],
						["Pain"],
						["GERD"],
						["Edema"],
						["Allergies",", ","Asthma",", ","Inflammation"],
						["Anxiety",", ","Depression"],
						["Bipolar Disorder",", ","Bulimia",", ","Depression",", ","Obsessive-Compulsive Disorder",", ","Premenstrual Dysphoric Disorder"],
						["Hypercholesterolemia"],
						["Depression",", ","Smoking Cessation"],
						["Bacterial"," ","Infection"],
						["ADHD",", ","Narcolepsy"],
						["Depression"],
						["Anxiety",", ","Depression",", ","Pain"],
						["Immunosuppression",", ","Inflammation"],
						["Benign Prostatic Hyperplasia (BPH)"],
						["Pain"],
						["Depression"],
						["Pain"],
						["Hypercholesterolemia"],
						["HFrEF",", ","Hypertension"],
						["Hypokalemia"],
						["Pain"],
						["Myocardial Infarction"],
						["Type 1"," ","Diabetes",", ","Type 2"," ","Diabetes"],
						["Fever",", ","Myocardial Infarction",", ","Pain",", ","Stroke"],
						["Angina",", ","Hypertension",", ","Myocardial Infarction"],
						["Anxiety",", ","Depression"],
						["Anxiety"],
						["Acne",", ","Contraception",", ","Osteoporosis Prevention",", ","Menopause Vasomotor Symptoms"],
						["Gout"],
						["Hypertension"],
						["Muscle Spasm"],
						["Anxiety",", ","Seizures"],
						["Insomnia"],
						["Bacterial"," ","Infection"],
						["Pain"],
						["Anticoagulation",", ","Myocardial Infarction"],
						["ADHD",", ","Narcolepsy"],
						["Anticoagulation"],
						["Type 2"," ","Diabetes"],
						["Vitamin D"," ","Deficiency"],
						["Bipolar Disorder",", ","Depression",", ","Schizophrenia"],
						["Asthma",", ","COPD"],
						["Breast Cancer",", ","Hypoestrogenism",", ","Osteoporosis Prevention",", ","Prostate Cancer",", ","Menopause Vasomotor Symptoms",", ","Vulvar and Vaginal Atrophy"],
						["Pain"],
						["Nausea",", ","Vomiting"],
						["Dysmenorrhea",", ","Pain",", ","Inflammation"],
						["Type 2"," ","Diabetes"],
						["HFrEF",", ","Hypertension",", ","Primary Hyperaldosteronism"],
						["ADHD",", ","Hypertension"],
						["Type 1"," ","Diabetes",", ","Type 2"," ","Diabetes"],
						["Allergies"],
						["Allergies"],
						["Migraine",", ","Seizures"],
						["Anxiety",", ","Seizures"],
						["Acne",", ","Contraception"],
						["Bipolar Disorder",", ","Seizures"],
						["Angina",", ","Arrhythmias",", ","Hypertension"],
						["Hypertension"],
						["Pain"],
						["Allergies",", ","Anxiety"],
						["Anxiety"],
						["Glaucoma"],
						["Anxiety",", ","Depression",", ","Obsessive-Compulsive Disorder",", ","Posttraumatic Stress Disorder",", ","Premenstrual Dysphoric Disorder",", ","Menopause Vasomotor Symptoms"],
						["ADHD",", ","Binge Eating Disorder"],
						["Asthma",", ","COPD"],
						["Neuralgia",", ","Seizures"],
						["Angina",", ","Arrhythmias",", ","Tremor",", ","Hypertension",", ","Migraine",", ","Myocardial Infarction"],
						["Bacterial"," ","Infection"],
						["Vitamin D"," ","Deficiency"],
						["Type 1"," ","Diabetes",", ","Type 2"," ","Diabetes"],
						["Benign Prostatic Hyperplasia (BPH)",", ","Male Pattern Hair Loss"],
						["Hypercholesterolemia",", ","Hypertriglyceridemia"],
						["Type 2"," ","Diabetes"],
						["Anemia"],
						["Bacterial"," ","Infection"],
						["Anticoagulation"],
						["Muscle Spasm"],
						["Bacterial"," ","Infection"],
						["Depression"],
						["Hypercholesterolemia"],
						["Osteoporosis"],
						["Seizures"],
						["Migraine"],
						["Hypertension"],
						["Bacterial"," ","Infection"],
						["Bipolar Disorder",", ","Depression",", ","Schizophrenia",", ","Tourette Disorder"],
						["Inflammation",", ","Dysmenorrhea",", ","Pain"],
						["Iron"," ","Deficiency"],
						["GERD"],
						["Cough"],
						["Depression"],
						["Allergies",", ","Inflammation"],
						["Hypercholesterolemia"],
						["Asthma",", ","COPD"],
						["Viral"," ","Infection"],
						["Immunosuppression"],
						["Overactive Bladder"],
						["Bacterial"," ","Infection"],
						["Bipolar Disorder",", ","Seizures",", ","Migraine"],
						["Edema",", ","Hypertension"],
						["Hypothyroidism"],
						["Alcohol Withdrawal Syndrome",", ","Anxiety",", ","Muscle Spasm",", ","Seizures"],
						["Angina",", ","Hypertension"],
						["Bacterial"," ","Infection"],
						["Alzheimer Disease"],
						["Type 1"," ","Diabetes",", ","Type 2"," ","Diabetes"],
						["Lupus",", ","Malaria",", ","Rheumatoid Arthritis"],
						["Angina"],
						["Contraception"],
						["Muscle Spasm"],
						["Male Hypogonadism"],
						["GERD"],
						["Contraception"],
						["Influenza"],
						["Hypertension"],
						["ADHD"],
						["Asthma",", ","COPD"],
						["Fungal"," ","Infection"],
						["Type 2"," ","Diabetes"],
						["Edema",", ","Hypertension"],
						["Muscle Spasm"],
						["HFrEF",", ","Hypertension"],
						["Bacterial"," ","Infection"],
						["Immunosuppression",", ","Inflammation"],
						["ADHD",", ","Hypertension"],
						["Angina",", ","Arrythmia",", ","Hypertension"],
						["Type 2"," ","Diabetes",", ","Weight Loss"],
						["Abnormal Uterine Bleeding",", ","Amenorrhea",", ","Contraception",", ","Endometriosis"],
						["Parkinson Disease",", ","Restless Legs Syndrome"],
						["Fever",", ","Pain"],
						["Heart Failure",", ","Type 2"," ","Diabetes"],
						["Adrenal Insufficiency",", ","Inflammation",", ","Ulcerative Colitis"],	
						["Acne",", ","Contraception",", ","Premenstrual Dysphoric Disorder"],
						["Bipolar Disorder",", ","Schizophrenia"],
						["Motion Sickness",", ","Vertigo"],
						["COPD"],
						["Immunosuppression"],
						["Depression"],
						["HFrEF",", ","Hypertension",", ","Myocardial Infarction"],
						["Vitamin B12"," ","Deficiency"],
						["Contraception"],
						["Viral"," ","Infection"],
						["Weight Loss"],
						["Bacterial"," ","Infection"],
						["Glaucoma",", ","Hypertension",", ","Migraine",", ","Myocardial Infarction"],
						["Immunosuppression",", ","Inflammation"],
						["Seizures"],
						["Pain"],
						["Hypertension"],
						["Irritable Bowel Syndrome"],
						["Parkinson Disease",", ","Restless Legs Syndrome"],
						["Allergies"],
						["Type 1"," ","Diabetes",", ","Type 2"," ","Diabetes"],
						["Alzheimer Disease"],
						["Hypertension"],
						["Fungal"," ","Infection"],
						["Migraine"],
						["Pain"],
						["Nausea",", ","Vomiting"],
						["Type 2"," ","Diabetes"],
						["Breast Cancer"],
						["Depression"],
						["HFrEF",", ","Hypertension"],
						["Type 2"," ","Diabetes"],
						["Inflammation"],
						["Hypertension"],
						["Bacterial"," ","Infection"],
						["Arrythmias"],
						["Angina"],
						["Agitation",", ","Bipolar Disorder",", ","Depression",", ","Schizophrenia"],
						["Duodenal Ulcers"],
						["Constipation"],
						["Abnormal Uterine Bleeding",", ","Amenorrhea"],
						["Overactive Bladder"],
						["Bacterial"," ","Infection"],
						["Hypertension"],
						["Bacterial"," ","Infection"],
						["Allergies"],
						["Hyperthyroidism"],
						["Immunosuppression"],
						["Erectile Dysfunction",", ","Pulmonary Arterial Hypertension"],
						["Bipolar Disorder",", ","Seizures",", ","Neuralgia"],
						["Hypertension"],
						["Calcium"," ","Deficiency"],
						["GERD"],
						["Asthma",", ","Allergies",", ","Crohn Disease",", ","Ulcerative Colitis"],
						["Gout"],
						["Benign Prostatic Hyperplasia (BPH)",", ","Hypertension"],
						["COPD"],
						["Bipolar Disorder"],
						["Atrial Fibrillation",", ","HFrEF"],
						["Glaucoma"],
						["Insomnia"],
						["Type 1"," ","Diabetes",", ","Type 2"," ","Diabetes"],
						["Benign Prostatic Hyperplasia (BPH)",", ","Hypertension"],
						["Angina"],
						["Hypertriglyceridemia"],
						["Hypertension"],	
						["Insomnia"],
						["Arrythmias"],
						["Myocardial Infarction"],
						["Glaucoma",", ","Rosacea"],
						["GERD"],
						["Anesthesia",", ","Pain"],
						["Bipolar Disorder",", ","Schizophrenia"],
						["Parkinsonism"],
						["Fungal"," ","Infection"],
						["Insomnia"],
						["Heart Failure"],
						["Calcium"," ","Deficiency"],
						["Fluid Loss",", ","Irrigation",", ","Moisturizer",", ","Sodium"," ","Deficiency"],
						["Edema",", ","Hypertension"],
						["Migraine"],
						["Ulcerative Colitis"],
						["Hypothyroidism"],
						["Opioid Use Disorder",", ","Pain"],
						["Bacterial"," ","Infection"],
						["Bacterial"," ","Infection"],
						["Depression",", ","Insomnia"],
						["Type 2"," ","Diabetes",", ","Weight Loss"],
						["Pain"],
						["Bacterial"," ","Infection"],
						["Hypertension"],
						["Allergies",", ","Asthma"],
						["Glaucoma"],
						["Edema"],	
						["Breast Cancer"],
						["Type 2"," ","Diabetes"],
						["Acne"],
						["Acne",", ","Bacterial"," ","Infection"],
						["Allergies",", ","COPD"],
						["Constipation"],
						["COPD"],
						["Hypertension"],
						["Hyperparathyroidism",", ","Plaque Psoriasis"],
						["Smoking Cessation"],
						["Anaphylaxis"],
						["Abnormal Uterine Bleeding",", ","Breast Cancer",", ","Hypoestrogenism",", ","Osteoporosis Prevention",", ","Prostate Cancer",", ","Menopause Vasomotor Symptoms",", ","Vulvar and Vaginal Atrophy"],
						["Type 2"," ","Diabetes"],
						["Cough"],
						["Constipation",", ","Magnesiun"," ","Deficiency"],
						["Contraception"],
						["Arrythmias"],
						["Eyelash Hypotrichosis",", ","Glaucoma"],
						["Type 1"," ","Diabetes",", ","Type 2"," ","Diabetes"],
						["Abnormal Uterine Bleeding",", ","Amenorrhea",", ","Contraception",", ","Endometriosis"],
						["Breast Cancer"],
						["Allergies",", ","Asthma"],
						["Rheumatoid Arthritis",", ","Ulcerative Colitis"],
						["Glaucoma"],
						["Pain"],
						["Pain"],
						["ADHD"],
						["Allergies"],
						["Hypertension"],
						["Seizures"],
						["Opioid Use Disorder"],
						["Breast Cancer",", ","Osteoporosis"],
						["Inflammation"],
						["Alcohol Use Disorder",", ","Opioid Use Disorder"],
						["Bacterial"," ","Infection"],
						["Fungal"," ","Infection"],
						["Pain"],
						["Allergies"],
						["Hypertension"],
						["Pancreatic Insufficiency"],
						["Seizures"],
						["Allergies"],
						["Migraine"],
						["Constipation"],
						["Cough"],
						["Hypertriglyceridemia"],
						["Multiple Sclerosis"],
						["Benign Prostatic Hyperplasia (BPH)",", ","Erectile Dysfunction",", ","Pulmonary Arterial Hypertension"],
						["Type 2"," ","Diabetes"],
						["HIV"],
						["Overactive Bladder"],
						["Immunosuppression"],
						["HFrEF",", ","Hypertension"],
						["Constipation"],
						["Inflammation"],
						["Overactive Bladder"],
						["Type 1"," ","Diabetes",", ","Type 2"," ","Diabetes"],
						["Antiseptic"],
						["Inflammation"]];

	/* dosage forms */					
var drugDosageForms = [["Tablet"],
					["Capsule","IV","Oral Liquid","Tablet"],
					["Oral Liquid","Tablet"],
					["ER Tablet","Oral Liquid","Tablet"],
					["ER Sprinkle Capsule","ER Tablet","IV","Tablet"],
					["Oral Suspension","Tablet"],
					["Aerosol","Nebulization Solution","Oral Liquid","Tablet"],
					["DR Capsule","DR Tablet","Oral Packet"],
					["Tablet"],
					["Capsule","ER Capsule","Oral Liquid","Tablet"],
					["Capsule","Tablet"],
					["Capsule","Oral Liquid","Tablet"],
					["Oral Suspension","Tablet"],
					["Chewable Tablet","Oral Packet","Tablet"],
					["Oral Liquid","Tablet"],
					["DR Tablet","IV","Oral Packet"],
					["IM","IV","Oral Liquid","SubQ","Tablet"],
					["Aerosol","Cream","Lotion","Nasal Liquid","Ointment"],
					["Oral Liquid","Tablet"],
					["Capsule","DR Capsule","Oral Liquid","Tablet"],
					["Sprinkle Capsule","Tablet"],
					["ER Tablet","Tablet"],
					["Capsule","Chewable Tablet","Oral Suspension","Tablet"],
					["ER Capsule, Tablet"],
					["Tablet"],
					["DR Capsule","DR Sprinkle Capsule"],
					["DR Tablet","Oral Liquid","Tablet"],
					["Capsule"],
					["Capsule","Chewable Tablet","IV","Oral Suspension","Tablet"],
					["Capsule","Oral Liquid","Tablet"],
					["Capsule","IV","Tablet"],
					["Tablet"],
					["ER Capsule","Tablet"],
					["ER Sprinkle Capsule","ER Tablet","IV","Oral Liquid","Oral Packet","Tablet"],
					["ER Capsule","ER Tablet","Oral Liquid","Tablet"],
					["Tablet"],
					["SubQ"],
					["Capsule","Chewable Tablet","DR Tablet","Enteric Coated Tablet","ER Capsule","Rectal Suppository"],
					["Tablet"],
					["ER Capsule","ER Tablet","Tablet"],
					["ER Tablet","ODT Tablet","Oral Liquid","Tablet"],
					["Capsule","Chewable Tablet","Tablet"],
					["IV","Tablet"],
					["Tablet"],
					["ER Capsule","Tablet"],
					["ODT Tablet","Tablet"],
					["ER Tablet","Oral Liquid","Sublingual Tablet","Tablet"],
					["IV","Opthalmic Liquid","Oral Packet","Oral Suspension","Tablet"],
					["Capsule","ER Capsule","ER Tablet","Oral Liquid","Tablet"],
					["Tablet"],
					["Chewable Tablet","ER Capsule","ER Chewable Tablet","ER ODT Tablet","ER Oral Suspension","ER Tablet","Oral Liquid","Patch","Tablet"],
					["Tablet"],
					["ER Tablet","Tablet"],
					["Capsule","Oral Liquid","Tablet"],
					["ER Tablet","Tablet"],
					["Aerosol"],
					["Cream","External Solution","Gel","IM Oil","Patch","Tablet","Vaginal Insert","Vaginal Ring","Vaginal Tablet"],
					["Oral Liquid","Tablet"],
					["IM","IV","ODT Tablet","Oral Film","Oral Liquid","Tablet"],
					["Capsule","DR Tablet","ER Tablet","Oral Suspension","Tablet"],
					["Tablet"],
					["Oral Suspension","Tablet"],
					["Epidural Solution","ER Tablet","Patch","Tablet"],
					["IV","SubQ"],
					["Capsule","Chewable Tablet","ODT Tablet","Oral Liquid"],
					["Capsule","Chewable Tablet","IV","ODT Tablet","Oral Liquid","Tablet"],
					["ER Sprinkle Capsule","Oral Liquid","Sprinkle Capsule","Tablet"],
					["ER Sprinkle Capsule","IM","IV","Oral Liquid","Tablet"],
					["Tablet"],
					["Chewable Tablet","ER Tablet","ODT Tablet","Tablet"],
					["ER Capsule","ER Tablet","IV","Tablet"],
					["Tablet"],
					["Capsule","Cream","DR Tablet","ER Tablet","External Solution","Gel","Opthalmic Liquid","Oral Packet","Patch","Tablet"],
					["Capsule","IM","Oral Liquid","Tablet"],
					["Tablet"],
					["Opthalmic Liquid"],
					["Capsule","ER Tablet","Oral Suspension","Tablet"],
					["Capsule","Chewable Tablet"],
					["Aerosol"],
					["Capsule","ER Tablet","Oral Liquid"],
					["ER Capsule","IV","Oral Liquid","Tablet"],
					["Capsule","Oral Suspension","Tablet"],
					["Capsule","Chewable Tablet","Oral Liquid","Sublingual Liquid","Tablet"],
					["IV","SubQ"],
					["Tablet"],
					["Capsule","DR Capsule","Tablet"],
					["Tablet"],
					["Capsule","IM","IV","SubQ","Tablet"],
					["Capsule", "DR Capsule","DR Tablet","IV","Oral Liquid","Oral Suspension","Tablet"],
					["Oral Suspension","Tablet"],
					["Capsule","Tablet"],
					["Chewable Tablet","ER Tablet","Oral Suspension","Tablet"],
					["Tablet"],
					["ER Tablet","Tablet"],
					["Effervescent Tablet","Oral Liquid","Tablet"],
					["ER Tablet","IV","ODT Tablet","Oral Liquid","Tablet"],
					["Nasal Liquid","Nasal Powder","SubQ","Tablet"],
					["IM","IV","Tablet"],
					["IV","Oral Suspension","Tablet"],
					["IM","ODT Tablet","Oral Liquid","Tablet"],
					["Capsule","Oral Liquid"],
					["DR Tablet","ER Tablet","Oral Liquid","Tablet"],
					["IV","Oral Suspension","Tablet"],
					["Capsule"],
					["ODT Tablet","Tablet"],
					["Aerosol","Cream","IM","Intra-Articular Injection","Intraocular Suspension","IV","Lotion","Nasal Liquid","Ointment","Paste"],
					["Tablet"],
					["Aerosol"],
					["Tablet"],
					["IM","IV","Oral Liquid","SubQ","Tablet"],
					["ER Tablet","Gel","Oral Liquid","Patch","Tablet"],
					["ER Tablet","IV","Opthalmic Liquid","Opthalmic Ointment","Oral Suspension","Otic Solution","Tablet"],
					["Capsule","DR Sprinkle Capsule","DR Tablet","ER Tablet","IV","Oral Liquid"],
					["Capsule","Tablet"],
					["Tablet"],
					["IM","IV","Nasal Liquid","Oral Liquid","Rectal Gel","Tablet"],
					["Capsule","ER Tablet"],
					["Capsule","External Solution","External Swab","Foam","Gel","IM","IV","Lotion","Oral Liquid","Vaginal Cream","Vaginal Suppository"],
					["ODT Tablet","Tablet"],
					["SubQ"],
					["Tablet"],
					["ER Tablet","Tablet"],
					["Patch","Tablet"],
					["Intrathecal Solution","Oral Liquid","Oral Suspension","Tablet"],
					["Buccal Tablet","Capsule","External Solution","Gel","IM","Patch","Pellet Implant"],
					["DR Capsule","DR Tablet","IV","Oral Packet"],
					["Tablet"],
					["Capsule","Oral Suspension"],
					["Tablet"],
					["ER Capsule","Tablet"],
					["Aerosol","Inhalation Capsule"],
					["IV","Oral Suspension","Tablet"],
					["SubQ"],
					["Tablet"],
					["IM","IV","Tablet"],
					["Oral Liquid","Tablet"],
					["Capsule","Cream","Gel","IV","Lotion","Tablet","Vaginal Gel"],
					["ODT Tablet","Opthalmic Liquid","Oral Liquid","Tablet"],
					["ER Tablet","Tablet"],
					["ER Capsule","ER Tablet","IV","Tablet"],
					["SubQ"],
					["Tablet"],
					["ER Tablet","Tablet"],
					["Capsule","Chewable Tablet","ER Tablet","IV","Oral Gel","Oral Liquid","Oral Packet","Oral Suspension","Rectal Suppository","Tablet"],
					["Tablet"],
					["Cream","External Solution","Foam","IM","IV","Lotion","Ointment","Rectal Enema","Rectal Suppository","Sprinkle Capsule","Tablet"],
					["Tablet"],
					["IM","ODT Tablet","Oral Liquid","SubQ","Tablet"],
					["Chewable Tablet","Tablet"],
					["Nebulization Solution"],
					["SubQ"],
					["Capsule","Oral Liquid"],
					["Tablet"],
					["ER Tablet","IM","Lozenge","Nasal Liquid","Sublingual Liquid","Sublingual Tablet","SubQ","Tablet"],
					["Vaginal Ring"],
					["Buccal Tablet","Capsule","Cream","IV","Ointment","Oral Suspension","Tablet"],
					["Capsule","Tablet"],
					["Capsule","Oral Suspension"],
					["Opthalmic Gel","Opthalmic Liquid","Tablet"],
					["IM","IV","Tablet"],
					["ER Tablet","Oral Suspension","Tablet"],
					["ER Capsule","ER Tablet","IM","IV","Oral Liquid","Rectal Suppository","Tablet"],
					["Tablet"],
					["Capsule","IM","Oral Liquid","Tablet"],
					["ER Tablet","Tablet"],
					["Nasal Liquid","Opthalmic Liquid"],
					["SubQ"],
					["ER Capsule","Oral Liquid","Tablet"],
					["Capsule"],
					["Cream","Foam","Gel","Shampoo","Tablet"],
					["ODT Tablet","Tablet"],
					["Oral Liquid","Tablet"],
					["IM","IV","Oral Liquid","Rectal Suppository","Tablet"],
					["ER Tablet","Tablet"],
					["Tablet"],
					["ER Tablet"],
					["Capsule"],
					["Tablet"],
					["Cream","External Solution","Foam","Gel","Lotion","Ointment","Shampoo"],
					["Tablet"],
					["Inhalation Solution","IV","Opthalmic Liquid","Oral Liquid","Tablet"],
					["IV","Tablet"],
					["Aerosol","ER Capsule","IV","Ointment","Patch","Rectal Ointment","Sublingual Packet","Sublingual Tablet","Translingual Solution"],
					["IM","ODT Tablet","Tablet"],
					["Oral Suspension","Tablet"],
					["Capsule","Oral Liquid","Rectal Enema","Tablet"],
					["Capsule","IM Oil","Vaginal Gel","Vaginal Insert"],
					["ER Oral Suspension","ER Tablet"],
					["Cream","Ointment"],
					["Tablet"],
					["Capsule","Oral Suspension"],
					["Oral Liquid","Tablet"],
					["Tablet"],
					["Capsule","IV","Opthalmic Liquid","Oral Liquid"],
					["IV","Oral Suspension","Tablet"],
					["Chewable Tablet","ER Capsule","ER Tablet","Oral Suspension","Tablet"],
					["IV","Tablet"],
					["Capsule","Chewable Tablet","Oral Liquid","Oral Packet","Tablet","Wafer"],
					["DR Capsule","DR ODT Tablet"],
					["Aerosol","DR Capsule","DR Capsule Particles","ER Capsule","ER Tablet","Inhalation Suspension","Nasal Liquid","Rectal Foam"],
					["Capsule","Oral Liquid","Tablet"],
					["Capsule"],
					["Aerosol"],
					["Capsule","ER Tablet","Oral Liquid","Tablet"],
					["IM","IV","Oral Liquid","Tablet"],
					["Opthalmic Liquid"],
					["Capsule","Chewable Tablet","Gummies","Oral Liquid","Quick Dissolve Tablet","Tablet"],
					["SubQ"],
					["ER Tablet","Tablet"],
					["ER Tablet"],
					["Tablet"],
					["Capsule"],
					["Capsule"],
					["Tablet"],
					["Tablet"],
					["Gel","Opthalmic Liquid"],
					["DR Capsule"],
					["Aerosol","Cream","External Pad","External Solution","Gel","Intradermal Jet-Injector","Intraspinal Solution","IV","Liquid","Lotion","Ointment","Opthalmic Gel","Patch","Rectal Suppository","SubQ"],
					["Tablet"],
					["IM","IV","Tablet"],
					["Capsule","Cream","External Powder","Ointment","Oral Powder","Oral Suspension","Tablet"],
					["Tablet"],
					["Tablet"],
					["Capsule","Granules","Tablet"],
					["Aerosol","External Solution","Irrigation Solution","IV","Nasal Gel","Nasal Liquid","Nasal Swab","Nebulization Solution","Opthalmic Liquid","Opthalmic Ointment","Oral Liquid","Oral Powder","Tablet"],
					["Tablet"],
					["Capsule","Oral Liquid","Tablet"],
					["DR Capsule","DR Tablet","ER Capsule","Rectal Enema","Rectal Suppository"],
					["IV","Tablet"],
					["Buccal Film","IM","IV","Patch","Subcutaneous Implant","Sublingual Tablet","SubQ"],
					["Opthalmic Liquid","Otic Solution","Tablet"],
					["DR Capsule Particles","DR Tablet","External Pad","External Solution","Gel","IV","Opthalmic Ointment","Oral Suspension","Tablet"],
					["Capsule","Cream","Oral Liquid","Tablet"],
					["SubQ","Tablet"],
					["ER Tablet","IM","IV","Oral Liquid","Rectal Suppository","SubQ","Tablet"],
					["Oral Liquid","Tablet"],
					["Tablet"],
					["Aerosol","Cream","Nasal Liquid"],
					["Opthalmic Liquid"],
					["IM","IV","Tablet"],
					["Tablet"],
					["Tablet"],
					["Capsule","Cream","Gel","Lotion"],
					["Capsule","ER Capsule","ER Tablet","IV","Tablet"],
					["Aerosol","Inhalation Solution","Nasal Liquid"],
					["Oral Packet","Oral Powder"],
					["Aerosol"],
					["Tablet"],
					["Capsule","IV","Ointment","Oral Liquid"],
					["Tablet"],
					["IM","IV","Nasal Liquid","Nebulization Solution","SubQ"],
					["IM","IV","Tablet","Vaginal Cream"],
					["Tablet"],
					["ER Tablet","Oral Liquid","Oral Packet","Tablet"],
					["Capsule","Granules","IM","IV","Oral Liquid","Oral Packet","Tablet"],
					["Tablet"],
					["IV","Oral Liquid","Tablet"],
					["External Solution","Intraocular Impant","Opthalmic Liquid"],
					["SubQ"],
					["IM","SubQ","Tablet"],
					["Oral Liquid","Tablet"],
					["Aerosol","Cream","External Solution","Nasal Implant","Nasal Liquid","Ointment"],
					["DR Tablet","Tablet"],
					["Opthalmic Liquid"],
					["IM","IV","Nasal Liquid","Opthalmic Liquid","Tablet"],
					["Capsule","ER Capsule","IV","Oral Suspension","Rectal Suppository"],
					["Capsule"],
					["Nasal Liquid","Opthalmic Liquid"],
					["Tablet"],
					["Capsule","Chewable Tablet","IV","Oral Suspension"],
					["Buccal Film","Sublingual Film","Sublingual Tablet"],
					["Tablet"],
					["Opthalmic Liquid","Opthalmic Ointment"],
					["IM","Tablet"],
					["Opthalmic Liquid"],
					["Cream","External Solution","Gel","Tablet"],
					["Buccal Lozenge","Buccal Tablet","IM","IV","Nasal Liquid","Patch","Sublingual Liquid","Sublingual Tablet"],
					["Capsule","Chewable Tablet","IM","IV","Oral Liquid","Tablet"],
					["Tablet"],
					["DR Capsule","Tablet"],
					["Capsule"],
					["ODT Tablet","Oral Suspension","Tablet"],
					["SubQ"],
					["Capsule"],
					["Oral Liquid"],
					["Capsule","DR Capsule"],
					["DR Capsule"],
					["Tablet"],
					["Tablet"],
					["Tablet"],
					["ER Capsule","Tablet"],
					["SubQ"],
					["Tablet"],
					["Capsule","Tablet"],
					["Cream","Emulsion","Foam","Gel","IM","Lotion","Ointment"],
					["Oral Suspension","Tablet"],
					["IV","SubQ"],
					["Oral Liquid","External Pad","External Solution"],
					["Cream","External Solution","Gel","Ointment",]];

var randomizedIndexes = [241,
	92,
	257,
	147,
	270,
	71,
	262,
	43,
	136,
	163,
	208,
	55,
	61,
	16,
	124,
	150,
	128,
	168,
	129,
	283,
	165,
	140,
	239,
	95,
	247,
	42,
	204,
	286,
	24,
	179,
	132,
	206,
	19,
	236,
	205,
	2,
	33,
	101,
	5,
	138,
	274,
	254,
	269,
	89,
	139,
	102,
	287,
	201,
	214,
	108,
	193,
	153,
	159,
	119,
	246,
	90,
	207,
	282,
	104,
	35,
	38,
	259,
	294,
	133,
	235,
	151,
	182,
	181,
	78,
	23,
	112,
	213,
	279,
	111,
	196,
	107,
	265,
	59,
	44,
	297,
	154,
	180,
	50,
	9,
	49,
	93,
	52,
	144,
	271,
	1,
	65,
	7,
	131,
	4,
	58,
	288,
	252,
	164,
	103,
	106,
	175,
	222,
	56,
	278,
	261,
	200,
	190,
	57,
	255,
	263,
	36,
	125,
	67,
	217,
	178,
	251,
	32,
	75,
	293,
	224,
	15,
	115,
	231,
	148,
	212,
	253,
	199,
	121,
	30,
	160,
	69,
	296,
	18,
	245,
	157,
	41,
	264,
	240,
	221,
	203,
	85,
	243,
	158,
	161,
	66,
	209,
	238,
	233,
	162,
	25,
	183,
	172,
	63,
	53,
	250,
	21,
	26,
	60,
	118,
	96,
	195,
	197,
	142,
	198,
	256,
	227,
	229,
	137,
	218,
	202,
	272,
	87,
	244,
	48,
	74,
	29,
	141,
	285,
	13,
	289,
	51,
	8,
	45,
	28,
	12,
	173,
	11,
	260,
	273,
	22,
	117,
	292,
	122,
	130,
	110,
	149,
	226,
	291,
	152,
	225,
	281,
	210,
	169,
	223,
	54,
	146,
	187,
	176,
	116,
	68,
	40,
	249,
	170,
	100,
	219,
	81,
	14,
	113,
	91,
	215,
	143,
	79,
	6,
	234,
	83,
	228,
	220,
	64,
	248,
	194,
	145,
	174,
	232,
	134,
	88,
	0,
	284,
	191,
	192,
	84,
	20,
	185,
	80,
	34,
	135,
	70,
	268,
	290,
	17,
	295,
	266,
	171,
	98,
	86,
	277,
	37,
	127,
	73,
	211,
	216,
	10,
	156,
	39,
	189,
	276,
	155,
	3,
	82,
	280,
	114,
	230,
	97,
	76,
	31,
	188,
	77,
	126,
	242,
	109,
	167,
	237,
	166,
	267,
	72,
	46,
	99,
	62,
	120,
	186,
	47,
	123,
	258,
	177,
	94,
	105,
	27,
	298,
	275,
	184]